remove failing influx testcases
when influx was refactored these test cases must not
have been removed

>       influx._write_data(measurement, field, timestamp, tags)
E       AttributeError: 'module' object has no attribute '_write_data'

Change-Id: I78814266fae04bd3b0bc06fe1fe41317ba8aced4
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>