Update patch set 3
Patch Set 3:

ImportError: No module named 'django'

looks like we need to add django to requirements.txt maybe?

Patch-set: 3
Label: Verified=0