NSB: Fix cannot parse <address> 'bus' attribute
Add missing 0x prefix to bus attribute.

Error encountered:
* virsh create returns 'Failed to create domain from /tmp/vm_sriov_0.xml\n'
  error: internal error: Cannot parse <address> 'bus' attribute

Change-Id: I22e95c488e27d6e2a8fdf6c1a07faab275fa6bba
Signed-off-by: Dino Simeon Madarang <dinox.madarang@intel.com>
Reviewed-by: Alain Jebara <alain.jebara@intel.com>
Reviewed-by: Deepak S <deepak.s@linux.intel.com>
Reviewed-by: Ross Brattain <ross.b.brattain@intel.com>