NSB: Fix IndexError in pin_vcpu_for_perf
This addresses the IndexError in Standalone SRIOV/OVSDPDK context.
The correct sys_cpu number should be sys_cpu-1

Error:
    threads = "%s-%s" % (soc_cpu[socket][sys_cpu], soc_cpu[socket][-1])
IndexError: list index out of range

Tested platform: (Hyper-Threading disabled)
NUMA node0 CPU(s):     0-21
NUMA node1 CPU(s):     22-43

With socket equal to 0, sys_cpu value was 22 which resulted to IndexError.

Change-Id: I36b045cacce4caff4b5ddafaa9b6737f1c6df0a1
Signed-off-by: Dino Simeon Madarang <dinox.madarang@intel.com>
Reviewed-by: Alain Jebara <alain.jebara@intel.com>
Reviewed-by: Deepak S <deepak.s@linux.intel.com>
Reviewed-by: Ross Brattain <ross.b.brattain@intel.com>
Reviewed-by: Edward MacGillivray <edward.s.macgillivray@intel.com>
(cherry picked from commit 78fff64b00e255d7e4624bcc62faddc0d135e5a2)