remove trex install from run_tests.sh
We have mocked out all the Trex imports, so we don't need to download
the Trex library

It doesn't really make sense to down external libraries
each time we run unittests.  Trex is a large stand-alone package
and shouldn't really be used during unittests

Importing Trex caused some odd pyzmq import errors on Python 3

File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master
  /trex/scripts/external_libs/pyzmq-14.5.0/python3/fedora18
  /64bit/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'

Change-Id: I2ed06c0f88061baeff9ec96534cc59cca81924cc
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>