Update patch set 5
Patch Set 5:

Error: rst validatino (doc8) has failed, please fix the following error(s).
    docs/vTC/abbreviations.rst:2: D000 Title underline too short.
    docs/vTC/README.rst:6: D000 Title underline too short.
    docs/vTC/README.rst:66: D000 Unexpected indentation.
    docs/vTC/README.rst:65: D000 Definition list ends without a blank line; unexpected unindent.
    docs/vTC/README.rst:66: D000 Blank line required after table.
    docs/vTC/README.rst:67: D000 Inline substitution_reference start-string without end-string.
    docs/vTC/README.rst:68: D000 Inline substitution_reference start-string without end-string.
    docs/vTC/README.rst:69: D000 Inline substitution_reference start-string without end-string.
    docs/vTC/README.rst:67: D000 Line block ends without a blank line.
    docs/vTC/README.rst:71: D000 Block quote ends without a blank line; unexpected unindent.
    docs/templates/Yardstick_task_templates.rst:112: D001 Line too long
    docs/yardstick/opnfv_yardstick_tc001.rst:71: D005 No newline at end of file
    docs/yardstick/opnfv_yardstick_tc012.rst:6: D000 Malformed table.
Document link(s):
    http://artifacts.opnfv.org/yardstick/docs/docs/index.html
    http://artifacts.opnfv.org/yardstick/docs/docs/docs.pdf

Patch-set: 5