ssh: fix unittest race condition
os.stat is being called multiple times for some reason

we only care that is it called at some point.

======================================================================
FAIL: tests.unit.test_ssh.SSHRunTestCase.test__put_file_sftp
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/.tox/py3/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/tests/unit/test_ssh.py", line 458, in test__put_file_sftp
    mock_stat.assert_called_once_with("localfile")
  File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/.tox/py3/lib/python3.5/site-packages/mock/mock.py", line 947, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'stat' to be called once. Called 3 times.
Ran 1209 tests in 2.618s
FAILED (id=0, failures=1)
error: testr failed (1)
+ testr failing
======================================================================
FAIL: tests.unit.test_ssh.SSHRunTestCase.test__put_file_sftp
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/.tox/py3/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/tests/unit/test_ssh.py", line 458, in test__put_file_sftp
    mock_stat.assert_called_once_with("localfile")
  File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/.tox/py3/lib/python3.5/site-packages/mock/mock.py", line 947, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'stat' to be called once. Called 3 times.
Ran 1 tests in 0.110s
FAILED (id=0, failures=1)

Change-Id: I73370996e6e0543419eec8ecbe81be424ec15822
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>