update trex version for constants.so import bug
Previously before we disabled Trex in the unittests
we were hitting an error when running Python3.5,
see full description in 28209

https://gerrit.opnfv.org/gerrit/#/c/28209/

File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/trex/scripts/external_libs/pyzmq-14.5.0/python3/fedora18/64bit/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'

It looks like this was an actual upstream Trex bug
and it was fixed in

https://github.com/cisco-system-traffic-generator/trex-core/commit/9808fce2b0b3b5b7c9b28303e99486501a1cc10d
zmq: fix wrong constants.so (was used from 3.5 to both versions)
Yaroslav Brustinov <ybrustin@cisco.com>

This Trex fix should be in v2.20.

We don't test Trex in unitests, but people running
Trex on Python3 should hit this issue.

Change-Id: Ic914e48819d7fd3e951628f7c3d3778849da7d94
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>