fix unitest blocker: change os.path.exists mock
It looks like our global os.path mocks aren't working in Jenkins.
Presumably something is happening in parallel somewhere such
that when we mock patch os.path.exists it is sharing state.

Try to fix this by doing a local import of os.path.exists in the Heat module
and only patching that.

https://build.opnfv.org/ci/job/yardstick-verify-master/6970/consoleText

Traceback (most recent call last):
  File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/.tox/py3/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/yardstick/tests/unit/benchmark/contexts/test_heat.py", line 337, in test_deploy_ssh_key_before_adding_resources
    mock_path_exists.assert_called_with(key_filename)
  File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/.tox/py3/lib/python3.5/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 2, in raise_from
AssertionError: Expected call: exists('/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/yardstick/resources/files/yardstick_key-demo-12345678')
Actual call: exists('/home/jenkins/_netrc')

Change-Id: I4f7b41fbfe06f3abe1fadf801f3f20adf2c061d3
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>