ArgsAlreadyParsedError: arguments already parsed: cannot register CLI option
JIRA: YARDSTICK-216

When I call YardstickCLI  in flask, it will always encounter a
ArgsAlreadyParsedError if the API run test case more than two times.

In YardstickCLI, if I just call CONF.clear(), it will occur another
error due to other opts not unregister. I don’t know if the problem
is on the oslo.config side.

I solve the problem by unregister the opts.

Change-Id: Ic898c8d62625785ceb793c75e8210ac354ac63bf
Signed-off-by: chenjiankun <chenjiankun1@huawei.com>