BugFix: update to paramiko 1.18.0 to fix TypeError
with python 3 there is a paramiko error
due to .keys() usages in python 3

File "python3.5/site-packages/paramiko/ssh_exception.py", line 166, in __init__
  body = ', '.join([x[0] for x in addrs[:-1]
TypeError: 'dict_keys' object is not subscriptable

paramiko 1.16.0 tries to index addr.keys() but
addr.keys() is not a dict view in Python 3 and not a list
so we need to convert .keys() to a list, using sorted()

This was most recently fixed in
https://github.com/paramiko/paramiko/commit/0411010d55755913fa7bd5b0a9c719c8548549f4

which should be in paramiko 1.18.0

Change-Id: I6b10664611cab3b21d3aa33ecf1343ff134f59a1
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>