Add netifaces to dependencies
Netifaces package is used by oslo.utils but is not installed
automatically:

$ cd yardstick/
$ git checkout master
$ git pull
$ mkvirtualenv YS
$ easy_install -U setuptools
$ python setup.py develop
$ glance image-list
No module named netifaces
$ nova image-list
Traceback (most recent call last):
  File "/home/uabjnon/.virtualenvs/YS/bin/nova", line 9, in <module>
    load_entry_point('python-novaclient', 'console_scripts', 'nova')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 568, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2720, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2380, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2386, in resolve
  File "/home/uabjnon/.virtualenvs/YS/local/lib/python2.7/site-packages/python_novaclient-2.35.0-py2.7.egg/novaclient/shell.py", line 46, in <module>
    from novaclient import client
  File "/home/uabjnon/.virtualenvs/YS/local/lib/python2.7/site-packages/python_novaclient-2.35.0-py2.7.egg/novaclient/client.py", line 38, in <module>
    from oslo_utils import netutils
  File "/home/uabjnon/.virtualenvs/YS/local/lib/python2.7/site-packages/oslo.utils-3.1.0-py2.7.egg/oslo_utils/netutils.py", line 25, in <module>
    import netifaces
ImportError: No module named netifaces

Change-Id: Ie5e3dfad073d816ad982a56543eb3b77a818e029
Signed-off-by: Jo¶rgen Karlsson <jorgen.w.karlsson@ericsson.com>