Update patch set 3
Patch Set 3:

Error: rst validatino (doc8) has failed, please fix the following error(s).
    docs/vTC/README.rst:69: D000 Content block expected for the "code-block" directive; none found.
    docs/vTC/README.rst:79: D000 Unexpected indentation.
    docs/vTC/README.rst:78: D000 Definition list ends without a blank line; unexpected unindent.
    docs/vTC/README.rst:79: D000 Blank line required after table.
    docs/vTC/README.rst:80: D000 Inline substitution_reference start-string without end-string.
    docs/vTC/README.rst:81: D000 Inline substitution_reference start-string without end-string.
    docs/vTC/README.rst:82: D000 Inline substitution_reference start-string without end-string.
    docs/vTC/README.rst:80: D000 Line block ends without a blank line.
    docs/vTC/README.rst:84: D000 Block quote ends without a blank line; unexpected unindent.
    docs/templates/Yardstick_task_templates.rst:112: D001 Line too long
Error: PDF creation for docs/yardstick has failed, please fix source rst file(s).
Document link(s):
    http://artifacts.opnfv.org/review/4353/framework/index.html
    http://artifacts.opnfv.org/review/4353/framework/framework.pdf
    http://artifacts.opnfv.org/review/4353/yardstick/index.html

Patch-set: 3