Bugfix: 'module' object has no attribute 'UnsupportedExtension'
JIRA: YARDSTICK-1100

This Error occur when run kuberntes test case:
The Key is the pyopenssl dependency, it seems
YARDSTICK-1032(https://jira.opnfv.org/browse/YARDSTICK-1032) encounter
the same problem. I have checked that this dependency was first
introduced for git-review. So yardstick may not actually depend on it. I
have test it in heat context, and it works. So I remove it. But it still
need yardstick team to check.

Here it is the error log:
Traceback (most recent call last):
    File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
    File "/home/opnfv/repos/yardstick/yardstick/benchmark/core/task.py",
    line 301, in atexit_handler
    context.undeploy()
    File
    "/home/opnfv/repos/yardstick/yardstick/benchmark/contexts/kubernetes.py",
    line 63, in undeploy
    self._delete_ssh_key()
    File
    "/home/opnfv/repos/yardstick/yardstick/benchmark/contexts/kubernetes.py",
    line 133, in _delete_ssh_key
    k8s_utils.delete_config_map(self.ssh_key)
    File
    "/home/opnfv/repos/yardstick/yardstick/common/kubernetes_utils.py",
    line 179, in delete_config_map
    **kwargs)
    File
    "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/core_v1_api.py",
    line 9059, in delete_namespaced_config_map
    (data) = self.delete_namespaced_config_map_with_http_info(name,
            namespace, body, **kwargs)
    File
    "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/core_v1_api.py",
    line 9159, in delete_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
    File
    "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py",
    line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content,
    _request_timeout)
    File
    "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py",
    line 155, in __call_api
    _request_timeout=_request_timeout)
    File
    "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py",
    line 387, in request
    body=body)
    File
    "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py",
    line 256, in DELETE
    body=body)
    File
    "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py",
    line 166, in request
    headers=headers)
    File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py",
    line 66, in request
    **urlopen_kw)
    File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py",
    line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
    File
    "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py",
    line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
    File
    "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py",
    line 601, in urlopen
    chunked=chunked)
    File
    "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py",
    line 346, in _make_request
    self._validate_conn(conn)
    File
    "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py",
    line 850, in _validate_conn
    conn.connect()
    File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py",
    line 337, in connect
    cert = self.sock.getpeercert()
    File
    "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py",
    line 348, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
    File
    "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py",
    line 202, in get_subj_alt_name
    except (x509.DuplicateExtension, x509.UnsupportedExtension,
            AttributeError: 'module' object has no attribute
            'UnsupportedExtension'

Change-Id: Ib3c81a8bb00708201fa5ffdfc8bf3b96452a0e32
Signed-off-by: chenjiankun <chenjiankun1@huawei.com>