Debugging information when dpdk bind fails should be improved
JIRA: YARDSTICK-1585

When dpdk-devbind.py is failing, the information provided is poor,
making it difficult to debug.

At least the exact command used should be printed, ideally with the
returned error. As of today, the more interesting line is

DpdkBindHelperException: /opt/nsb_bin/dpdk-devbind.py command
failed with rc=1

Change-Id: I7831c81ffa9e1f4695480eb140fa97a58ff88f8c
Signed-off-by: Daniel Martin Buckley <daniel.m.buckley@intel.com>