Update patch set 9
Patch Set 9:

> I cloned Danube and did a test. The creation of the 2nd context
 > failed as follows, I am looking at if this can be improved.
 > 
 > 2017-04-12 13:41:41,324 yardstick.orchestrator.heat heat.py:485
 > INFO Creating stack 'yardstick-TC008-1938bc24'
 > 2017-04-12 13:41:44,199 yardstick.orchestrator.heat heat.py:503
 > DEBUG stack state CREATE_IN_PROGRESS
 > 2017-04-12 13:41:46,587 yardstick.orchestrator.heat heat.py:503
 > DEBUG stack state CREATE_IN_PROGRESS
 > 2017-04-12 13:41:49,025 yardstick.orchestrator.heat heat.py:503
 > DEBUG stack state CREATE_FAILED
 > error: failed to deploy stack: 'Resource CREATE failed:
 > IpAddressInUseClient: resources.yardstick-TC008-1938bc24-test-sriov-router-if0:
 > Unable to complete operation for network da175ec1-7f73-42e8-baf6-f41fee252094.
 > The IP address 10.0.1.1 is in use.'

hello,
This question is because you create two interface for a network which you created, the interface is as a gateway of this network. You could add this interface to two routers. But can't create two interface, So the code there is not support two yardstick process for your TC008.

Patch-set: 9
Label: Verified=0